-- Inserts English -----------------------------------------------------------------------------------------------------
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (0, 'EN', 'Iron Man', 'Robert Downey Jr.', 'Iron Man (Anthony Edward "Tony" Stark) is a fictional superhero appearing in American comic books published by Marvel Comics. The character was co-created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and Jack Kirby...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59598/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (1, 'EN', 'Spider-Man', 'Tom Holland', 'Spider-Man is a fictional superhero created by writer-editor Stan Lee and writer-artist Steve Ditko. He first appeared in the anthology comic book Amazing Fantasy #15 (August 1962) in the Silver Age of Comic Books...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59595/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (2, 'EN', 'American Captain', 'Chris Evans', 'Captain America (Steve Rogers) is a fictional superhero appearing in American comic books published by Marvel Comics. Created by cartoonists Joe Simon and Jack Kirby, the character first appeared in Captain America Comics #1 (cover dated March 1941) from Timely Comics, a predecessor of Marvel Comics...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59598/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (3, 'EN', 'Black Widow', 'Scarlett Johansson', 'Natalia Alianovna Romanova (alias: Natasha Romanoff), colloquial: Black Widow is a fictional superhero appearing in American comic books published by Marvel Comics...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59601/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (4, 'EN', 'Thor', 'Chris Hemsworth', 'In Germanic mythology, Thor is a hammer-wielding god associated with thunder, lightning, storms, oak trees, strength, the protection of mankind, and also hallowing and fertility. Besides Old Norse Porr, extensions of the god occur in Old English as Punor, and in Old High German as Donar...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59602/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (5, 'EN', 'Hulk', 'Mark Ruffalo', 'The Hulk is a fictional superhero appearing in publications by the American publisher Marvel Comics. Created by writer Stan Lee and artist Jack Kirby, the character first appeared in the debut issue of The Incredible Hulk (May 1962)...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59592/preview.svg');

-- Inserts Spanish -----------------------------------------------------------------------------------------------------
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (6, 'SP', 'Iron Man', 'Robert Downey Jr.', 'Iron Man (en espanol El hombre de hierro), es un superheroe de Marvel Comics. Tras el apodo se encuentra el famoso multimillonario Anthony Edward Stark, mas conocido como Tony Stark...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59598/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (7, 'SP', 'Spider-Man', 'Tom Holland', 'Spider-Man (llamado Hombre Arana en muchas de las traducciones al espanol) es un superheroe ficticio creado por los escritores y editores Stan Lee y Steve Ditko. Aparecio por primera vez en el comic de antologia Amazing Fantasy # 15 (agosto de 1962) en la Edad de Plata de los comics...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59595/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (8, 'SP', 'Capitan America', 'Chris Evans', 'Capitan America (en ingles Captain America), cuyo nombre real es Steven Grant Rogers, mejor conocido como Steve Rogers, es un superheroe y justiciero ficticio que aparece en comics estadounidenses publicados por Marvel Comics. Creado por los historietistas Joe Simon y Jack Kirby, el personaje aparecio por primera vez en Captain America Comics #1 (marzo de 1941) de Timely Comics, predecesor de Marvel Comics...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59598/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (9, 'SP', 'Viuda Negra', 'Scarlett Johansson', 'Natalia Alianovna Romanova,1(alias: Natasha Romanoff), coloquial: Viuda Negra (en ingles: Black Widow) es una superheroina ficticia que aparece en el comic estadounidense y libros publicados por Marvel Comics...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59601/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (10, 'SP', 'Thor', 'Chris Hemsworth', 'Thor es el dios del trueno y fuerza en la mitologia nordica y germanica. Su papel es complejo ya que tenia influencia en areas muy diferentes, tales como el clima, las cosechas, la proteccion, la consagracion, la justicia, las lidias, los viajes y las batallas...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59602/preview.svg');
INSERT INTO AVENGER (ID, LANG, NAME, ACTOR, DESCRIPTION, URLIMAGE) VALUES (11, 'SP', 'Hulk', 'Mark Ruffalo', 'Hulk es un personaje ficticio, un superheroe que aparece en los comics estadounidenses publicados por la editorial Marvel Comics. El personaje fue creado por los escritores Stan Lee y Jack Kirby siendo su primera aparicion en The Incredible Hulk #1 publicado en mayo de 1962...', 'https://d29fhpw069ctt2.cloudfront.net/icon/image/59592/preview.svg');


COMMIT;